### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by JosephMDavis** [quentinsf/IMAPdedup#24] opened 2015-03-30 17:41 UTC
I am getting the following when I try to run this script against a SmarterMail mail server:

There are 7850 messages in INBOX/Old Mail - Keep.
Traceback (most recent call last):
  File "./imapdedup.py", line 313, in <module>
    main(sys.argv[1:])
  File "./imapdedup.py", line 310, in main
    process(options, mboxes)
  File "./imapdedup.py", line 222, in process
    deleted = check_response(server.search(None, 'DELETED'))[0].split()
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by quentinsf** [comment] 2015-03-30 20:21
Hi Joe - 

Mmm... I haven't seen that one before, though I gather from some searching that SmarterMail does use its own IMAP server: it may not be fully compliant.  

Does it do this on other mailboxes, or just that one?

And do you have a single account there, or might you be able to create a temporary account for me to experiment with?  

Otherwise, you could try inserting the line:

     imaplib.Debug = 4

in the script.  This will cause the interactions between the script and the server to be printed out: you can look at the last few lines before it dies and post them here?

Many thanks,
Quentin

**Comment by quentinsf** [comment] 2020-02-28 21:16
OK, I think this is now fixed in the latest version.

**Closed by quentinsf** 2020-02-28 21:16 UTC

**Comment by backelj** [comment] 2021-03-20 23:38
Hi @quentinsf 

I bumped into the same error today, with the error occurring in line 308 of imapdedup.py:

```
304    deleted_info = check_response(server.search(None, query))
305    if deleted_info:
306        # If neither None nor empty, then
307        # the first item should be a list of msg ids
308        resp = [int(n) for n in deleted_info[0].split()]
```

The `deleted_info` is [None], so it looks like line 305 should be changed to `if deleted_info[0]` ...

-- Franky

**Comment by quentinsf** [comment] 2021-04-22 18:37
Thanks @backelj  - and sorry for the delay.

I can't reproduce this here so can't test it, but I've changed it to:

`if deleted_info and deleted_info[0]:`

in the latest version, which I hope should deal with this.
